### ISSUE TITLE
Use enumerations when possible

### ISSUE THREAD

**Issue by mbouchenoire** [go-ive/steam-api#20]
#17 removed classes that provided no value to the library's clients, but most of those classes could have been replaced by enumerations, as values are not dynamic. Enumerations would be useful for clients for obvious reasons.

**Comment by go-ive** [comment]
The reason I decided to not use enums is that I would have to manually update them whenever Steam introduced new values. It's a bit of a lazy approach, I agree, but this makes the project more maintainable.

Which classes would you have replaced?

**Comment by mbouchenoire** [comment]
I would create these enums :
- Category
- Genre
- SupportedLanguage (which would conveniently reference the corresponding Locale)

You could deal with new (unexpected) values with a wildcard value ("Unsupported" for example).

Note that this change would break the current API and would be included in a 6.0 release (as far as I understand 5.0 is out).

**Comment by go-ive** [comment]
I kinda have to disagree on this approach, even if it is a cleaner strategy.

The reason is twofold:
1.) Using enums, I would have to keep track of a huge set of values and update them as soon as valve decides to add or remove some.
2.) Failing to do this would lead to many "Undefined" values to be returned, which is actually data loss. Having a string may not be the greatest way to go about it, but it is surely easier to debug and find why a specific category/or whatever could not be matched.
